# [START cloudbuild_basic_config]
steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:experimental']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:1.0-experimental']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-docker.pkg.dev/wp-cloudrun-demo/wordpress/wordpress-1.0:latest', 
           '.']
    env: 
      - "DOCKER_BUILDKIT=1"

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-docker.pkg.dev/wp-cloudrun-demo/wordpress/wordpress-1.0:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'wp-gcloud-run', '--image', 'us-docker.pkg.dev/wp-cloudrun-demo/wordpress/wordpress-1.0:latest', '--region', 'us-central-1']
images:
- us-docker.pkg.dev/wp-cloudrun-demo/wordpress/wordpress-1.0:latest
# [END cloudbuild_basic_config]