steps:
    # Get the secret from Secret Manager
  - name: 'gcr.io/cloud-builders/secretmanager'
    args:
      - 'secret_version:latest'
      - 'access_token'
      - 'projects/$PROJECT_ID/secrets/gcs-json-file'
    secretEnv:
      - '_ACCESS_TOKEN'
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - pull
      - docker/dockerfile:experimental
      - pull
      - docker/dockerfile:1.0-experimental
      - build
        -t
        - us-docker.pkg.dev/$PROJECT_ID/wordpress/wordpress-1.0:latest
        - '_ACCESS_TOKEN=${_ACCESS_TOKEN}'
        - .
    env:
      - DOCKER_BUILDKIT=1

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
        - us-docker.pkg.dev/$PROJECT_ID/wordpress/wordpress-1.0:latest

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
        - deploy
        - wp-gcloud-run
        - --image
        - us-docker.pkg.dev/$PROJECT_ID/wordpress/wordpress-1.0:latest
        - --region
        - us-central1

images:
  - us-docker.pkg.dev/$PROJECT_ID/wordpress/wordpress-1.0:latest